### PR TITLE
Feature/verify mongbdob object id shape

### PR DESCRIPTION
**Pull request by courtneymyers**
Verify the "id" parameter passed to the server routes (which corresponds with a submission ID) is the correct shape to be a MongoDB ObjectId before the server app makes calls to the Forms.gov web services for getting, creating, and updating rebate form submissions.

### CODE REVIEW

**Comment by courtneymyers** [comment]
@dpgalloway can you take a look at this when you have a moment? As long as the Forms.gov folks aren't doing anything custom with the way the MongoDB object Ids are being set, this shouldn't affect real form submissions and should prevent a lot of the bogus API calls from the scanner from hitting their servers.

**Comment by courtneymyers** [comment]
@dpgalloway ohhhh, one thing to point out: I changed one of the helpdesk API calls: I changed the `router.post("/rebate-form-submission/:id")` to a `router.get("/reopen-rebate-form-submission/:id")` – I'm still doing a PUT inside that server routes controller/callback but realized I didn't need to do a POST from the client app, as I already have the user's email address from the cookie in the server app.

So you'll want to update our OpenAPI/Swagger file with that route change before the next scan.

**Comment by dpgalloway** [comment]
@courtneymyers  This looks good to me! Only thing you could update is moving verifyMongoObjectId to come before the checkBapComboKeys in the couple routes that use both. This way we'd avoid hitting BAP again if we don't need to (the 400 will return before BAP is called). Not necessary but could help reduce the load on BAP's server if the scanner does a lot of these invalid ID requests.

**Comment by courtneymyers** [comment]
> @courtneymyers This looks good to me! Only thing you could update is moving verifyMongoObjectId to come before the checkBapComboKeys in the couple routes that use both. This way we'd avoid hitting BAP again if we don't need to (the 400 will return before BAP is called). Not necessary but could help reduce the load on BAP's server if the scanner does a lot of these invalid ID requests.

Good suggestions, @dpgalloway!

**Comment by dpgalloway** [comment]
> @dpgalloway ohhhh, one thing to point out: I changed one of the helpdesk API calls: I changed the `router.post("/rebate-form-submission/:id")` to a `router.get("/reopen-rebate-form-submission/:id")` – I'm still doing a PUT inside that server routes controller/callback but realized I didn't need to do a POST from the client app, as I already have the user's email address from the cookie in the server app.
> 
> So you'll want to update our OpenAPI/Swagger file with that route change before the next scan.

OK I thought on this a little more and think it would be better in terms of security/scanning to change this back to a post. It's not affecting functionality and not enforced, but since the endpoint does change state in our app (i.e. changes the form status and doesn't just get form data), it should be a post or put. 

Since our token cookie is sameSite=lax, in theory this could be vulnerable to CSRF: A helpdesk user is logged into CSB, on some random website from another tab they unintentionally click a link to "app.epa.gov/csb/help/reopen-rebate-form-submission/12345". The sameSite=lax setting allows the cookie to be passed on cross-site GET requests and therefore the link works and the form is updated.

**Comment by courtneymyers** [comment]
> > @dpgalloway ohhhh, one thing to point out: I changed one of the helpdesk API calls: I changed the `router.post("/rebate-form-submission/:id")` to a `router.get("/reopen-rebate-form-submission/:id")` – I'm still doing a PUT inside that server routes controller/callback but realized I didn't need to do a POST from the client app, as I already have the user's email address from the cookie in the server app.
> > So you'll want to update our OpenAPI/Swagger file with that route change before the next scan.
> 
> OK I thought on this a little more and think it would be better in terms of security/scanning to change this back to a post. It's not affecting functionality and not enforced, but since the endpoint does change state in our app (i.e. changes the form status and doesn't just get form data), it should be a post or put.
> 
> Since our token cookie is sameSite=lax, in theory this could be vulnerable to CSRF: A helpdesk user is logged into CSB, on some random website from another tab they unintentionally click a link to "app.epa.gov/csb/help/reopen-rebate-form-submission/12345". The sameSite=lax setting allows the cookie to be passed on cross-site GET requests and therefore the link works and the form is updated.

I hear you – I think this is a bigger CSRF discussion... POST requests are still vulnerable to CSRF attacks – it's not as easy as creating a malicious link, but a hidden form can be submitted on page load...it's more work for an attacker to do, but not impossible. But I see your point – still marginally safer to switch back to a POST.

My main reason for the GET was to prevent the scanner from attempting to submit a bogus payload to the Forms.gov web service in a POST request's body (that's assuming they passed in a string that's a valid MongoDB ObjectId in the request URL, so it gets past the `verifyMongoObjectId` middleware). But maybe we should validate the POST body before submitting... I like to think Forms.gov does all this on their end, but maybe not. I wish we knew what caused their server issues...

So I think there's a few outstanding things we can do here:
1) CSRF prevention
2) Validating POST body before submitting to Forms.gov (overkill maybe? but still could do some simple validation before submitting)

For this PR, I'll change it back to a POST though – we can chat more in a bit...

**Comment by courtneymyers** [comment]
@dpgalloway thanks for discussing. As I understand it, switching back to a POST should get around the CSRF issue w/ the cookie settings you're setting, and posting an empty object from the client to the server will prevent the scanner from trying to post bogus data, since we're setting the fields in the server controller/callback – so best of both worlds. Another great suggestion!

If you're able to re-test these small changes, that'd be great. And please feel free to merge this in if all looks good to you...otherwise happy to discuss further tomorrow.

**Pull request merged**
